name: Prepare release
on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Version as prerelease'
        required: false
        default: false
        type: boolean

jobs:
  call-min-flutter-test:
    uses: ./.github/workflows/test.yml
    with:
      flutter_version: '3.13.0'
      fatal_warnings: false
  prepare-release:
    name: Prepare release
    needs: call-min-flutter-test
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - name: Remove invalid pub files # TODO(gustl22): remove when fixed: https://github.com/dart-lang/pub/pull/4145
        run: |
          rm example/assets/coins_non_ascii_и.wav
          rm example/server/public/files/audio/coins_non_ascii_и.wav
        working-directory: packages/audioplayers
        shell: bash
      - uses: bluefireteam/melos-action@v3
        with:
          run-versioning: ${{ inputs.prerelease == false }}
          run-versioning-prerelease: ${{ inputs.prerelease == true }}
          publish-dry-run: true
          create-pr: true
